### PR TITLE
Web app

### PR DESCRIPTION
**Pull request by fbongiovanni29**
Pulls raw json file from github should update page automatically when json file is updated

Organizes with company name as header as link to site then address and positions fall under as p tags

Needs styling and navigation see styles.txt, fellow classmates may work on this or myself.

### CODE REVIEW

**Comment by mcelaney** [comment]
Hey @devNoiseConsulting can you have a look at this if you get a minute?  If not I'll try to have a look when I get some more time next week...

**Comment by fbongiovanni29** [comment]
Yeah, let me know if there's anything that needs fixing, I tried to keep it as simple as possible. Might be working with people to style it at Code for Philly tonight

**Comment by devNoiseConsulting** [comment]
@mcelaney I can look at it.
@fbongiovanni29 It looks fine, but planning on styling it soon then I'll wait to merge this pull request. If your open to using Bootstrap, then I suggest adding the their CSS from a CDN. Then maybe think about using the styling for Panel with list group found at http://getbootstrap.com/components/#list-group for each company.

**Comment by fbongiovanni29** [comment]
Big thanks to Grady Fields for helping me convert that ugly jQuery to Angular last night at Code for Philly just tied up the rest of the kinks he has some bootstrap waiting for me tomorrow I'll e-mail him in the morning. Might try and add some type of nav/search functionality too.

**Pull request merged**
