### PR TITLE
More companies

### PR DESCRIPTION
**Pull request by devNoiseConsulting**
Reviewed past contacts and added companies that had career pages.

### CODE REVIEW

**Comment by mcelaney** [comment]
This would be the first NJ company... I'm already iffy on including the PA burbs in philadelphia.json...

What do you think about splitting the json files by county?  Or am I over thinking it?

**Comment by devNoiseConsulting** [comment]
As a burb dweller, I vote on including companies from the general metropolitan area. With the geolocation data it should be easy to filter the companies to smaller regions.

**Comment by devNoiseConsulting** [comment]
Split companies out into individual files and created a script to merge them back into a Philadelphia or Suburb file. 
Using the city limit data file from Open Data Philly. Do you think we should commit the file to the project or just document downloading it for the merge process?

**Comment by mcelaney** [comment]
I would document downloading it for the merge process... that way we can get refer to where it's maintained.

**Pull request merged**
